### ISSUE TITLE
error 启动之后无法访问https域名服务

### ISSUE THREAD

**Issue by happytrudy** [kurmanovd/tailscale-derper#1]
![Uploading 1640267163(1).png…]()

**Comment by happytrudy** [comment]
![1640267163(1)](https://user-images.githubusercontent.com/61214170/147249147-59435a29-ea43-47b4-b392-4e4c6000a357.png)

**Comment by kurmanovd** [comment]
Try: `derper --hostname www.dubux.ltd --certmode letsencrypt --certdir /certs --stun true`
